---
- hosts: all
  vars:
    - tests_container: ghcr.io/szyminson/ctr-tools-test:v0.3.4
    - in_container_result_dir: /var/ctr-tools-test/results
    - docker_result_dir: /tmp/docker-results
    - podman_result_dir: /tmp/podman-results
  tasks:
    - name: Check if Docker is installed
      ansible.builtin.command: docker --version
      register: docker_installed
      ignore_errors: true
      tags:
        - docker
        - tests
        - results

    - name: Create Docker result dir
      ansible.builtin.file:
        path: "{{ docker_result_dir }}"
        state: directory
      when: docker_installed.rc == 0
      tags:
        - docker
        - tests

    - name: Docker pull test container image
      community.docker.docker_image:
        name: "{{ tests_container }}"
        source: pull
      when: docker_installed.rc == 0
      tags:
        - docker
        - tests
  
    - name: Run Docker test
      community.docker.docker_container:
        name: ctr-tools-test
        image: "{{ tests_container }}"
        detach: false
        volumes:
          - "{{ docker_result_dir }}:{{ in_container_result_dir }}"
      when: docker_installed.rc == 0
      tags:
        - docker
        - tests
    
    - name: Get Docker results
      ansible.builtin.fetch:
        src: "{{ docker_result_dir }}/latest.json"
        dest: ./results
      when: docker_installed.rc == 0
      tags:
        - docker
        - results

    - name: Check if Podman is installed
      ansible.builtin.command: podman --version
      register: podman_installed
      ignore_errors: true
      tags:
        - podman
        - tests
        - results

    - name: Create Podman result dir
      ansible.builtin.file:
        path: "{{ podman_result_dir }}"
        state: directory
      when: podman_installed.rc == 0
      tags:
        - podman
        - tests

    - name: Podman pull test container image
      containers.podman.podman_image:
        name: "{{ tests_container }}"
      when: podman_installed.rc == 0
      tags:
        - podman
        - tests

    - name: Run Podman test
      containers.podman.podman_container:
        name: ctr-tools-test
        image: "{{ tests_container }}"
        detach: false
        volumes:
          - "{{ podman_result_dir }}:{{ in_container_result_dir }}"
      when: podman_installed.rc == 0
      tags:
        - podman
        - tests
    
    - name: Get Podman results
      ansible.builtin.fetch:
        src: "{{ podman_result_dir }}/latest.json"
        dest: ./results
      when: podman_installed.rc == 0
      tags:
        - podman
        - results

  


